# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Internship', 'Internship'), ('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], max_length=20)),
                ('category', models.CharField(choices=[('Account Management', 'Account Management'), ('Business & Strategy', 'Business & Strategy'), ('Creative & Design', 'Creative & Design'), ('Customer Service', 'Customer Service'), ('Data Science', 'Data Science'), ('Editorial', 'Editorial'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Fundraising & Development', 'Fundraising & Development'), ('Healthcare & Medicine', 'Healthcare & Medicine'), ('HR & Recruiting', 'HR & Recruiting'), ('Legal', 'Legal'), ('Marketing & PR', 'Marketing & PR'), ('Operations', 'Operations'), ('Project & Product Management', 'Project & Product Management'), ('Retail', 'Retail'), ('Sales', 'Sales'), ('Social Media & Community', 'Social Media & Community')], max_length=50)),
                ('contents', models.TextField(default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.Company')),
            ],
        ),
    ]
